spring.application.name=Order-management-system
logging.file.name=C:\\Users\\SaiSmrithiMuthukumar\\git_repo\\Weekend_Assignments\\Order-management-system\\src\\main\\java\\com\\order_management\\Order_management_system\\logs\\execution.log
