spring.application.name=member-service
server.port=8081
logging.file.name=C:\\Users\\SaiSmrithiMuthukumar\\git_repo\\Weekend_Assignments\\Order-management-system-microservices attempt\\member\\logs\\member-service.log